/* The proper definitions for FreeMiNT's sigaction.
   Copyright (C) 1993-1999, 2000 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public License as
   published by the Free Software Foundation; either version 2 of the
   License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public
   License along with the GNU C Library; if not, see
   <https://www.gnu.org/licenses/>.  */

/* Modified for MiNTLib by Mehdi Medour  */

#ifndef _SIGNAL_H
# error "Never include <bits/siginfo.h> directly; use <signal.h> instead."
#endif

/* POSIX real-time signal extensions */

#ifndef _SIGVAL_DEFINED
#define _SIGVAL_DEFINED

/* Signal value union */
union sigval {
	long int sival_int;         /* Integer value */
	void *sival_ptr;       /* Pointer value */
};

#endif /* _SIGVAL_DEFINED */

#ifndef _SIGINFO_T_DEFINED
#define _SIGINFO_T_DEFINED

#define SA_SIGINFO     0x0040		/* Invoke signal-catching function with three arguments instead of one. */

/* siginfo_t structure for extended signal information
 * Note: Uses internal __pid_t and __uid_t to avoid dependency issues
 */
// typedef struct {
// 	int si_signo;           /* Signal number */
// 	int si_code;            /* Signal code */
// 	int si_errno;           /* If non-zero, an errno value */
// 	short si_pid;           /* Sending process ID */
// 	unsigned short si_uid;  /* Real user ID of sending process */
// 	void *si_addr;          /* Address of faulting instruction */
// 	int si_status;          /* Exit value or signal */
// 	long si_band;           /* Band event for SIGPOLL */
// 	union sigval si_value;  /* Signal value */
// } siginfo_t;
typedef struct {
	long int si_signo;           /* Signal number */
	long int si_code;            /* Signal code */
	long int si_errno;           /* If non-zero, an errno value */
	short si_pid;           /* Sending process ID (use short like kernel pid) */
	unsigned short si_uid;  /* Real user ID (use unsigned short) */
	void *si_addr;          /* Address of faulting instruction */
	long int si_status;          /* Exit value or signal */
	long si_band;           /* Band event for SIGPOLL */
	union sigval si_value;  /* Signal value */
} siginfo_t;

#endif /* _SIGINFO_T_DEFINED */

/* Signal codes for si_code */
#define SI_USER        0x0001    /* Signal sent by kill() or raise() */
#define SI_QUEUE       0x0002    /* Signal sent by sigqueue() */
#define SI_TIMER       0x0003    /* Signal generated by timer expiration */
#define SI_ASYNCIO     0x0004    /* Signal generated by async I/O completion */
#define SI_MESGQ       0x0005    /* Signal generated by message arrival */

/* Sub-codes for si_code when si_signo == SIGFPE */
#define FPE_INTDIV     0x0801    /* integer divide by zero */
#define FPE_INTOVF     0x0802    /* integer overflow */
#define FPE_FLTDIV     0x0803    /* floating point divide by zero */
#define FPE_FLTOVF     0x0804    /* floating point overflow */
#define FPE_FLTUND     0x0805    /* floating point underflow */
#define FPE_FLTRES     0x0806    /* floating point inexact result */
#define FPE_FLTINV     0x0807    /* invalid floating point operation */
#define FPE_FLTSUB     0x0808    /* subscript out of range */

/* For SIGCHLD */
#define CLD_EXITED     0x0601    /* Child has exited */
#define CLD_KILLED     0x0602    /* Child was killed */
#define CLD_DUMPED     0x0603    /* Child terminated abnormally */
#define CLD_TRAPPED    0x0604    /* Traced child has trapped */
#define CLD_STOPPED    0x0605    /* Child has stopped */
#define CLD_CONTINUED  0x0606    /* Stopped child has continued */
